language: python

matrix:
    include:
        - python: 3.4.5
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36

install:
    - pip install tox codecov
script:
    tox
after_success:
    codecov
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: jettify
    password:
        secure: V/UjH36QQcJyLqIzNb7/R1Y4nLJi1O2nvp/xf3O/myiO722QD6SZQ7u5CoWcicyQBhqodu/oXA2XeJk1LAorhKnk15CkiWhO7wFAWuYc4rQA7qgjApfercGPqcSL1K2RmGeP/UWpLR+La5o4/9zCmfG83Z007rmii9a6dbdJU7c=
    on:
        tags: true
        repo: aio-libs/aiohttp_sse
        all_branches: true
        python: 3.5
